using HotChocolate.Types;
using Microsoft.Extensions.DependencyInjection;

namespace HotChocolate.Extensions.Tracking;

public static class ObjectFieldDescriptorExtensions
{
    /// <summary>
    /// Makes a Field tracked with a custom TrackingEntry structure.
    /// This structure (Poco) is generated by the factory.
    /// </summary>
    /// <param name="fieldDescriptor">the HotChocolate Field</param>
    /// <param name="factory">The factory that generates the tracking entry.</param>
    /// <returns></returns>
    public static IObjectFieldDescriptor Track(
        this IObjectFieldDescriptor fieldDescriptor,
        ITrackingEntryFactory factory)
        => fieldDescriptor.Directive(new TrackedDirective(factory));

    /// <summary>
    /// Makes a Field tracked with a custom TrackingEntry structure.
    /// This structure (Poco) is generated by the factory.
    /// </summary>
    /// <param name="fieldDescriptor">the HotChocolate Field</param>
    /// <param name="factory">The factory that generates the tracking entry.</param>
    /// <returns></returns>
    public static IObjectFieldDescriptor Track<TFactory>(
        this IObjectFieldDescriptor fieldDescriptor)
        where TFactory : notnull, ITrackingEntryFactory
        => fieldDescriptor.Directive(new TrackedDirective(sp => sp.GetRequiredService<TFactory>()));
}
